import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import MainHeader from './components/Header/main-header';
import Footer from '@/components/Footer/Footer';
import AboutPage from './pages/about';

const getPageTitle = (route) => {
  switch (route) {
    case '/':
      return 'Home - Rahul Mamoria';
    case '/about':
      return 'About Me';
    case '/projects':
      return 'My Projects';
    case "/certificates":
      return "My Certificates"
    case "/contact-me":
      return "Contact Me"
    default:
      return 'Rahul Mamoria - Portfolio';
  }
};

const Layout = ({ children }) => {
  const router = useRouter();
  const title = getPageTitle(router.pathname);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <MainHeader />
    
      <main>{children}</main>

      <Footer />
    </>
  );
};

export default Layout;
