import Head from "next/head";
import MainHeader from "@/components/Header/main-header";
import HomePage from "@/components/Home/home";
// import EducationSection from "@/components/Education/education";
import Footer from "@/components/Footer/Footer";
import MySkills from "@/components/Skills/MySkills";
export default function Home() {
  return (
    <>
      <Head>
        <title>Rahul Mamoria - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.png" />
        
      </Head>
      <main >
       <HomePage/>
       {/* <EducationSection/> */}
       <MySkills/>
      </main>
    </>
  );
}
